<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#1.-[Chapter-08]-텍스트-분석" data-toc-modified-id="1.-[Chapter-08]-텍스트-분석-1">1. [Chapter 08] 텍스트 분석</a></span><ul class="toc-item"><li><span><a href="#1.1-텍스트-분석-이해" data-toc-modified-id="1.1-텍스트-분석-이해-1.1">1.1 텍스트 분석 이해</a></span></li><li><span><a href="#1.2-텍스트-사전-준비-작업(텍스트-전처리)---텍스트-정규화" data-toc-modified-id="1.2-텍스트-사전-준비-작업(텍스트-전처리)---텍스트-정규화-1.2">1.2 텍스트 사전 준비 작업(텍스트 전처리) - 텍스트 정규화</a></span><ul class="toc-item"><li><span><a href="#1.2.1-텍스트-토큰화" data-toc-modified-id="1.2.1-텍스트-토큰화-1.2.1">1.2.1 텍스트 토큰화</a></span></li><li><span><a href="#1.2.2-스톱-워드-제거" data-toc-modified-id="1.2.2-스톱-워드-제거-1.2.2">1.2.2 스톱 워드 제거</a></span></li><li><span><a href="#1.2.3-Stemming과-Lemmatization" data-toc-modified-id="1.2.3-Stemming과-Lemmatization-1.2.3">1.2.3 Stemming과 Lemmatization</a></span></li></ul></li><li><span><a href="#1.3-Bag-of-Words---BOW" data-toc-modified-id="1.3-Bag-of-Words---BOW-1.3">1.3 Bag of Words - BOW</a></span><ul class="toc-item"><li><span><a href="#1.3.1-BOW-피처-벡터화" data-toc-modified-id="1.3.1-BOW-피처-벡터화-1.3.1">1.3.1 BOW 피처 벡터화</a></span></li><li><span><a href="#1.3.2-사이킷런의-Count-및-TF-IDF-벡터화-구현" data-toc-modified-id="1.3.2-사이킷런의-Count-및-TF-IDF-벡터화-구현-1.3.2">1.3.2 사이킷런의 Count 및 TF-IDF 벡터화 구현</a></span></li><li><span><a href="#1.3.3-BOW-벡터화를-위한-희소-행렬" data-toc-modified-id="1.3.3-BOW-벡터화를-위한-희소-행렬-1.3.3">1.3.3 BOW 벡터화를 위한 희소 행렬</a></span></li><li><span><a href="#1.3.4-희소-행렬---COO-형식" data-toc-modified-id="1.3.4-희소-행렬---COO-형식-1.3.4">1.3.4 희소 행렬 - COO 형식</a></span></li><li><span><a href="#1.3.5-희소-행렬---CSR-형식" data-toc-modified-id="1.3.5-희소-행렬---CSR-형식-1.3.5">1.3.5 희소 행렬 - CSR 형식</a></span></li></ul></li><li><span><a href="#1.4-텍스트-분류-실습---20-뉴스그룹-분류" data-toc-modified-id="1.4-텍스트-분류-실습---20-뉴스그룹-분류-1.4">1.4 텍스트 분류 실습 - 20 뉴스그룹 분류</a></span></li><li><span><a href="#1.5-감성-분석" data-toc-modified-id="1.5-감성-분석-1.5">1.5 감성 분석</a></span></li></ul></li></ul></div>

# 1. [Chapter 08] 텍스트 분석

## 1.1 텍스트 분석 이해

- 텍스트 분류 : 문서가 특정 분류 또는 카테고리에 속하는 것을 예측하는 기법으로, 지도학습을 적용 (ex) 스팸 메일 검출)


- 감성 분석 : 텍스트에서 나타나는 감정/판단/믿음/의견 등의 주관적 요소를 분석하는 기법으로, 지도학습과 비지도학습 모두 적용 가능


- 텍스트 요약 : 텍스트 내에서 중요한 주제나 중심 사상을 추출하는 기법 (ex) 토픽 모델링)


- 텍스트 군집화와 유사도 측정 : 비슷한 유형의 문서에 대해 군집화를 수행하는 기법, 문서들간의 유사도를 측정해 비슷한 문서끼리 모을 수 있는 방법

**텍스트 분석 수행 프로세스**

1) 텍스트 전처리 : 대/소문자 변경, 특수문자 삭제 등의 클렌징 작업, 단어 등의 토큰화 작업, 의미 없는 단어 제거, 어근 추출 등의 텍스트 정규화 작업

2) 피처 벡터화/추출 : 텍스트에서 피처를 추출하고 여기에 특정 의미를 가지는 숫자형 값인 벡터 값 할당 (ex) BOW, Word2Vec)

3) ML 모델 수립 및 학습/예측/평가 : ML 모델을 적용해 학습/예측 및 평가 수행

## 1.2 텍스트 사전 준비 작업(텍스트 전처리) - 텍스트 정규화

- 클렌징 : HTML 태그나 특정 기호 등 불필요한 문자, 기호를 사전에 제거

### 1.2.1 텍스트 토큰화

- 문장 토큰화 : 문장의 마지막을 뜻하는 기호(. \n 등)에 따라 분리. 각 문장이 가지는 시맨틱적인 의미가 중요한 요소로 사용될 때 사용


**sent_tokenize()**를 이용해 문장 토큰화 수행

In [4]:
from nltk import sent_tokenize
import nltk
nltk.download('punkt')

text_sample = 'The Matrix is everywhere its all around us, here even in this room.\
               You can see it out your window or on your television.\
               You feel it when you go to work, or go to church or pay your taxes.'
sentences = sent_tokenize(text=text_sample)

print(type(sentences), len(sentences))
print(sentences)

<class 'list'> 3
['The Matrix is everywhere its all around us, here even in this room.', 'You can see it out your window or on your television.', 'You feel it when you go to work, or go to church or pay your taxes.']


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\dalgo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


- 단어 토큰화 : 공백, 콤마(,), 마침표(.), 개행문자 등으로 단어를 분리. BOW와 같이 단어의 순서가 중요하지 않은 경우 단어 토큰화만 사용해도 충분

**word_tokenize()**를 이용해 단어 토큰화 수행

In [5]:
from nltk import word_tokenize

sentence = 'The Matrix is everywhere its all around us, here even in this room.'
words = word_tokenize(sentence)
print(type(words), len(words))
print(words)

<class 'list'> 15
['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.']


In [6]:
# 여러 개의 문장으로 된 입력 데이터를 문장별로 단어 토큰화하게 만드는 함수 생성
def tokenize_text(text):
    # 문장 토큰화
    sentences = sent_tokenize(text)
    # 단어 토큰화
    word_tokens = [word_tokenize(sentence) for sentence in sentences]
    return word_tokens

# 여러 문장에 대해 문장별 단어 토큰화 수행
word_tokens = tokenize_text(text_sample)
print(type(word_tokens), len(word_tokens))
print(word_tokens)

<class 'list'> 3
[['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.'], ['You', 'can', 'see', 'it', 'out', 'your', 'window', 'or', 'on', 'your', 'television', '.'], ['You', 'feel', 'it', 'when', 'you', 'go', 'to', 'work', ',', 'or', 'go', 'to', 'church', 'or', 'pay', 'your', 'taxes', '.']]


단어 토큰화 수행 시 문맥적인 의미가 무시되는 문제를 해결하고자 도입된 것이 n-gram

n-gram은 연속적으로 2개의 단어들을 순차적으로 이동하면서 단어들을 토큰화

### 1.2.2 스톱 워드 제거

- 스톱 워드 제거 : 분석에 큰 의미가 없는 단어 제거

In [7]:
import nltk
nltk.download('stopwords')

print(len(nltk.corpus.stopwords.words('english')))
print(nltk.corpus.stopwords.words('english')[:20])

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\dalgo\AppData\Roaming\nltk_data...


179
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his']


[nltk_data]   Unzipping corpora\stopwords.zip.


In [8]:
stopwords = nltk.corpus.stopwords.words('english')
all_tokens = []

for sentence in word_tokens:
    filtered_words = []
    # 개별 문장별로 토큰화된 문장 list에 대해 스톱 워드를 제거
    for word in sentence:
        word = word.lower()   # 소문자 변환
        if word not in stopwords:
            filtered_words.append(word)
    all_tokens.append(filtered_words)

print(all_tokens)

[['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['see', 'window', 'television', '.'], ['feel', 'go', 'work', ',', 'go', 'church', 'pay', 'taxes', '.']]


### 1.2.3 Stemming과 Lemmatization

- Stemming : 단순화된 방법을 적용해 원래 단어에서 일부 철자가 훼손된 어근 단어를 추출하는 것

**LancasterStemmer()**를 이용해 Stemming 수행

In [9]:
from nltk.stem import LancasterStemmer
stemmer = LancasterStemmer()

print(stemmer.stem('working'), stemmer.stem('works'), stemmer.stem('worked'))
print(stemmer.stem('amusing'), stemmer.stem('amuses'), stemmer.stem('amused'))
print(stemmer.stem('happier'), stemmer.stem('happiest'))

work work work
amus amus amus
happy happiest


work의 경우 단순한 변화이므로 원형 단어를 제대로 인식하지만, amuse와 happy는 정확한 원형을 찾지 못함

- Lemmatization : 품사와 같은 문법적인 요소와 더 의미적인 부분을 감안해 정확한 철자로 된 어근 단어를 찾는 것 (시간이 더 오래 걸림)

**WordNetLemmatizer()**를 이용해 Lemmatization를 수행하며, 단어의 품사(v, a)를 같이 입력해야 함

In [10]:
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')

lemma = WordNetLemmatizer()
print(lemma.lemmatize('amusing', 'v'), lemma.lemmatize('amuses', 'v'), lemma.lemmatize('amused', 'v'))
print(lemma.lemmatize('happier', 'a'), lemma.lemmatize('happiest', 'a'))

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\dalgo\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip.


amuse amuse amuse
happy happy


## 1.3 Bag of Words - BOW

- BOW : 문맥이나 순서를 무시하고 일괄적으로 단어에 대해 빈도 값을 부여해 피처 값을 추출하는 모델

장점 : 쉽고 빠르며, 예상보다 문서의 특징을 잘 나타내어 여러 분야에서 활용도가 높음

단점 : 문맥 의미 반영이 부족하고, 희소 행렬 문제가 있음

cf) 희소 행렬 : 대규모의 칼럼으로 구성된 행렬에서 대부분의 값이 0으로 채워지는 행렬

### 1.3.1 BOW 피처 벡터화

- 카운트 벡터화 : 단어 피처에 값을 부여할 때 각 문서에서 해당 단어가 나타나는 횟수를 부여하는 경우. 값이 높을수록 중요한 단어로 인식


- TF-IDF : 기본적으로 자주 나타나는 단어에 높은 가중치를 주되, 모든 문서에서 자주 나타나는 범용적인 단어에는 페널티를 주는 방식

**문서마다 텍스트가 길고 문서의 개수가 많은 경우 TF-IDF 방식을 사용하는 것이 더 좋은 예측 성능을 보장**

### 1.3.2 사이킷런의 Count 및 TF-IDF 벡터화 구현

- **CountVectorizer()** 의 입력 파라미터

    max_df : 전체 문서에 걸쳐 너무 높은 빈도수를 가지는 단어 피처 제외
    
    min_df : 전체 문서에 걸쳐 너무 낮은 빈도수를 가지는 단어 피처 제외
    
    max_features : 추출하는 피처의 개수를 제한하며 정수로 값을 지정
    
    stop_words : english로 지정하면 영어의 스톱 워드 제외
    
    n_gram_range : BOW 모델의 단어 순서를 보강하기 위한 n_gram 범위 설정 (범위 최솟값, 범위 최댓값)
    
    analyzer, token_pattern, tokenizer
    
    
- CountVectorizer()를 이용한 피처 벡터화

    1) 사전 데이터 가공 : 모든 문자를 소문자로 변환하는 등 전처리 작업 수행

    2) 토큰화 : Default는 단어 기준(analyzer = True)이며, n_gram_range를 반영하여 토큰화 수행

    3) 텍스트 정규화 : stop words 필터링 수행 (Stemmer, Lemmatize는 자체 지원 X)

    4) 피처 벡터화 : max_df, min_df, max_features 등의 파라미터로 Token된 단어들을 feature extraction 후 vectorization 적용
    

- **TfidfVectorizer()**의 파라미터와 변환 방법은 CountVectorizer()와 동일

### 1.3.3 BOW 벡터화를 위한 희소 행렬

희소 행렬은 너무 많은 불필요한 0 값으로 인해 메모리 공간이 많이 필요하며, 연산 시에도 시간이 많이 소모됨

COO 형식과 CSR 형식으로 적은 메모리 공간을 차지할 수 있도록 변환할 수 있음

### 1.3.4 희소 행렬 - COO 형식

- COO 형식(Coordinate 좌표) : 0이 아닌 데이터와 그 데이터가 가리키는 행, 열의 위치를 별도의 배열로 저장하는 방식

**사이파이의 sparse.coo_matrix**를 이용해 희소 행렬 전환을 COO 형식으로 수행

In [11]:
import numpy as np

dense = np.array([[3,0,1], [0,2,0]])

In [12]:
from scipy import sparse

# 0이 아닌 데이터 추출
data = np.array([3,1,2])

# 행 위치와 열 위치를 각각 배열로 생성
row = np.array([0,0,1])
col = np.array([0,2,1])

# coo_matrix를 이용해 COO 형식으로 희소 행렬 생성
sparse_coo = sparse.coo_matrix((data, (row, col)))

In [13]:
sparse_coo.toarray()

array([[3, 0, 1],
       [0, 2, 0]])

### 1.3.5 희소 행렬 - CSR 형식

- CSR 형식(Compressed Sparse Row) : COO 형식이 반복적인 위치 데이터를 사용해야 하는 문제점을 해결한 것으로, 행 위치 배열 내에 있는 고유한 값의 시작 위치만 다시 별도의 위치 배열로 가지는 변환 방식

**사이파이의 sparse.csr_matrix**를 이용해 CSR 방식의 변환 수행

In [26]:
from scipy import sparse

dense2 = np.array([[0,0,1,0,0,5],
                   [1,4,0,3,2,5],
                   [0,6,0,3,0,0],
                   [2,0,0,0,0,0],
                   [0,0,0,7,0,8],
                   [1,0,0,0,0,0]])

# 0이 아닌 데이터 추출
data2 = np.array([1,5,1,4,3,2,5,6,3,2,7,8,1])

# 행 위치와 열 위치를 각각 배열로 생성
row = np.array([0,0,1,1,1,1,1,2,2,3,4,4,5])
col = np.array([2,5,0,1,3,4,5,1,3,0,3,5,0])

# COO 형식으로 변환
sparse_coo = sparse.coo_matrix((data2, (row, col)))

# 행 위치 배열의 고유한 값의 시작 위치 인덱스를 배열로 생성
row_ind = np.array([0,2,7,9,10,12,13])

# CSR 형식으로 변환
sparse_csr = sparse.csr_matrix((data2, col, row_ind))

print('COO 변환된 데이터가 제대로 되었는지 Dense로 출력 확인')
print(sparse_coo.toarray())
print('CSR 변환된 데이터가 제대로 되었는지 Dense로 출력 확인')
print(sparse_csr.toarray())

COO 변환된 데이터가 제대로 되었는지 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
CSR 변환된 데이터가 제대로 되었는지 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]


In [27]:
# 실제 사용 시에는 다음과 같이 밀집 행렬을 입력하여 COO, CSR 희소 행렬 생성
dense3 = np.array([[0,0,1,0,0,5],
                   [1,4,0,3,2,5],
                   [0,6,0,3,0,0],
                   [2,0,0,0,0,0],
                   [0,0,0,7,0,8],
                   [1,0,0,0,0,0]])

coo = sparse.coo_matrix(dense3)
csr = sparse.csr_matrix(dense3)

## 1.4 텍스트 분류 실습 - 20 뉴스그룹 분류

## 1.5 감성 분석